name: Language API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_USERNAME }}   # Hint: Access your username secret
          password: ${{ DOCKER_PASSWORD }}   # Hint: Access your password secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Hint: Format is username/image-name:tag
          tags: ${{ username/lang-api }}/lang-api:latest
